# A Simple Complaint Management System Application

In [ ]:
# For complaint management, here I take college system 
# complaints from students

In [12]:
import pandas as pd
import random

class college:
  def __init__(self):        
    self.complaints=[]

  def insert_complaint_toDict(self,id,name,dept,complaint):
    comp_id=str(random.randint(1000,9999))
    i=0
    while comp_id in self.complaints:
      comp_id=str(random.randint(1000,9999))
      i=i+1
    self.comp_table={}    
    self.comp_table['ID']=id
    self.comp_table['Name']=name
    self.comp_table['Department']=dept
    self.comp_table['Complaint_id']=comp_id
    self.comp_table['Complaint']=complaint    
    return comp_id
  
  def insert_dict_toList(self):
    self.complaints.append(self.comp_table)
    return print('\nYou have sucessfully registered your complaint...')

  def show_complaints(self):
    complaints=pd.DataFrame(self.complaints)
    return complaints
    


class student:
  def student_entry(self):
    id=input('Enter your id:')
    name=input('Enter your name:')
    dept=input('Enter your department name:')
    comp=input('Enter your complaint:')
    return id,name,dept,comp


college_1=college()
student_A=student()

In [20]:
def raise_your_complaint(): 
  entry=student_A.student_entry()
  comp_id=college_1.insert_complaint_toDict(entry[0],entry[1],entry[2],entry[3])
  college_1.insert_dict_toList()
  print(f'\nYour complaint id is {comp_id}.') 
  print('Please refer your complaint id for any changes in future...')
  
raise_your_complaint()

Enter your id:03
Enter your name:Saranya
Enter your department name:civil
Enter your complaint:comp3

You have sucessfully registered your complaint...

Your complaint id is 2470.
Please refer your complaint id for any changes in future...

In [22]:
def view_all_complaint():
  complaints_df=college_1.show_complaints()  
  return complaints_df

view_all_complaint()

   ID     Name  Department Complaint_id Complaint
0  01  Sathesh  mechanical         6630     comp1
1  03  Saranya       civil         2470     comp3

In [25]:
def update_complaint():
  while True:
    comp_id=input('Enter your complaint id:')
    compl_df=college_1.show_complaints()
    if comp_id in compl_df.Complaint_id.values:
      newComplaint=input('Enter your new complaint:')
      for i,dic in enumerate(college_1.complaints):
        if dic['Complaint_id']==comp_id in dic.values():
          college_1.complaints[i]['Complaint']=newComplaint
          print('\nUpdating complaint success...\n')          
      break
    else:
      print('\nEnter valid complaint id\n')

update_complaint()
view_all_complaint()

Enter your complaint id:123

Enter valid complaint id

Enter your complaint id:2470
Enter your new complaint:comp2

Updating complaint success...

   ID     Name  Department Complaint_id Complaint
0  01  Sathesh  mechanical         6630     comp1
1  03  Saranya       civil         2470     comp2

In [26]:

def remove_complaint():
  comp_id=input('Enter your complaint id:')
  complaints_df=college_1.show_complaints()
  if comp_id in complaints_df.Complaint_id.values:
    for i in range(len(college_1.complaints)):
      if college_1.complaints[i]['Complaint_id']==comp_id:
        del college_1.complaints[i]
        print('\nYour complaint has been removed successfully...')
  else:
    print('\nYou have no complaints or Enter valid complaint id...')
remove_complaint()

Enter your complaint id:2470

Your complaint has been removed successfully...

In [27]:
view_all_complaint()

   ID     Name  Department Complaint_id Complaint
0  01  Sathesh  mechanical         6630     comp1